# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ta2SkP5vXQeTxKLm6ql3Tl9PqNHkTT9f
"""

# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)
레모네이드.head()

# 독립, 종속
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

# 모델 만들기
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1) (X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

# 모델 학습
# verbose는 출력 OFF
model.fit(독립, 종속, epochs=1000, verbose=0)

# 모델 이용
model.predict(독립)

# Test
model.predict([[15]])