# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ta2SkP5vXQeTxKLm6ql3Tl9PqNHkTT9f
"""

# 라이브러리 사용
import pandas as pd

# 파일 읽어오기
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris2.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

# 칼럼의 데이터 타입 체크 - 품종이 int형! 이러면 안됨
# 품종이니까 category형으로 설정돼야 함
print(아이리스.dtypes)

# 원핫인코딩 - 인코딩이 되지 않는 현상 확인
(숫자는 숫자로만 읽음. category형으로 바꾸어줘야 함)
인코딩 = pd.get_dummies(아이리스)
print(인코딩.head())

# 품종 타입을 범주형으로 바꿔 주기
아이리스['품종'] = 아이리스['품종'].astype('category')
print(아이리스.dtypes)

# NA(NaN)값 체크
아이리스.isna().sum()
아이리스.tail() # 이건 뒤에 차트를 보여주는거임. head()와 반대

# NA(NaN)값을 가지고 연산할 시 오류가 발생할 수 있음
# 때문에 다른 값으로 바꿔줘야 함. 여기서는 평균값(mean)으로 변경

mean = 아이리스['꽃잎폭'].mean()
print(mean)
아이리스['꽃잎폭'] = 아이리스['꽃잎폭'].fillna(mean) # NA를 평균값으로 채우기
아이리스.tail()